goals:
  GYM_HEAD_RACK:
    frame_id: map
    x: 1.20
    y: 0.80
    z: 0.0
    yaw: 1.57

  GYM_TO_MEILIN_ENTRY:
    frame_id: map
    x: 3.50
    y: 1.20
    z: 0.0
    yaw: 0.0

  MEILIN_FLAT_TO_EXIT:
    frame_id: map
    x: 6.20
    y: -0.50
    z: 0.0
    yaw: -1.57

  MEILIN_TO_BATTLE_RAMP:
    frame_id: map
    x: 7.80
    y: 1.40
    z: 0.30
    yaw: 0.0
  TEST_PASSABLE_POINT:
    frame_id: map
    x: 6.1448036616089405
    y: 0.4948465767010584
    z: 0.20000000298023046
    yaw: 1.7786