cmd_vel_to_serial_node:
  ros__parameters:
    serial_port: "/dev/ttyUSB0"
    baud_rate: 115200
    linear_scale: 1000.0
    angular_scale: 1000.0
    max_vx: 0.08
    max_vy: 0.08
    max_wz: 0.10

    cmd_timeout: 0.3